### PR TITLE
One step towards config standardisation

### PR DESCRIPTION
**Pull request by skjnldsv**
One step towards a simple and global config.

@juliushaertl @christophwurst, what do you think? Maybe we should create a npm package to extend our webpack configs from?
Same goes for eslint and stylelint! :)

### CODE REVIEW

**Comment by juliushaertl** [comment]
> @juliushaertl @ChristophWurst, what do you think? Maybe we should create a npm package to extend our webpack configs from?

:+1: That would probably also save us some dependabot bumps if we have core dependencies like eslint defined in a wrapper package

**Comment by skjnldsv** [comment]
>  That would probably also save us some dependabot bumps if we have core dependencies like eslint defined in a wrapper package

How would that work? :)

**Comment by juliushaertl** [comment]
I imagined something like having a nextcloud-webpack-config package which exports the default configuration like https://raw.githubusercontent.com/skjnldsv/vueexample/ef19f4f26dd996d5a4eb911312460127774d48be/webpack.common.js and has all the loaders and webpack plugins as dependencies. As an app you then just need to define that one package as a dev dependency. But might be a bit to much, since it will make finding issues with updated dependencies harder.

**Comment by skjnldsv** [comment]
Can you have dependencies on a webpack config package?
That woulkd be awesome indeed!

**Comment by juliushaertl** [comment]
> Can you have dependencies on a webpack config package?
> That woulkd be awesome indeed!

I see not reason why that shouldn't work. I'll give it a try at some point.

**Comment by skjnldsv** [comment]
@juliushaertl let me try already :)

**Comment by skjnldsv** [comment]
> I imagined something like having a nextcloud-webpack-config package which exports the default configuration like [/webpack.common.js@`ef19f4f` (raw)](https://raw.githubusercontent.com/skjnldsv/vueexample/ef19f4f26dd996d5a4eb911312460127774d48be/webpack.common.js) and has all the loaders and webpack plugins as dependencies. As an app you then just need to define that one package as a dev dependency. But might be a bit to much, since it will make finding issues with updated dependencies harder.

Xell, it seems that you cannot :(
You cannot inherit dependencies in npm. github.com/npm/npm/issues/8112

We can still use the webpack global config though

**Pull request merged**
